import React, { setValue, setState, useState } from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Table from '../components/Table'
import Hero from '../components/Hero'
import { Jewels } from "../components/megalo";


export default function Home() {

  const [query, setQuery] = useState('')
  const search = (data) => {
      return data.filter((jewel) => jewel.notableName.toLowerCase().includes(query) || 
              jewel.description.toLowerCase().includes(query))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Megalomaniac Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <main className={styles.main}>
        <div className={styles.search}>
          <div className={styles.list}>
              <ul>
                  <li>elem 1</li>
              </ul>
          </div>

          <div className={styles.searchBox}>
              <input type="text" id="searchBox" placeholder="Search.."
                      onChange={e => setQuery(e.target.value.toLocaleLowerCase())} />
          </div>
        </div>

        <Table data={search(Jewels)} />
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  )
}
