import React, { useState } from 'react'
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import Hero from '../components/Hero'
import Table from '../components/Table'
import Search from '../components/Search'
import ScrollToTop from '../components/ScrollToTop'
import { data } from "../components/megalo"


export default function Home() {

  const [query, setQuery] = useState('')
  const [mods, setMod] = useState([])
  
  const search = (data) => {
      return data.filter((jewel) => jewel.name.toLowerCase().includes(query) || jewel.description.toLowerCase().includes(query))
  }

  const addItem = (mod) => {
    setMod(prevMods => {
      return !prevMods.includes(mod) ? [...prevMods, mod] : [...prevMods]
    })
  }

  const removeItem = (mod) => {
    setMod(current =>
      current.filter(currMod => {
        return currMod.name != mod.name
      }),
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Megalomaniac Lurker</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
      <main className={styles.main}>
        <Search setQuery={setQuery} mods={mods} removeItem={removeItem} />
        <Table data={search(data)} addItem={addItem} />
      </main>

      <ScrollToTop />

      <footer className={styles.footer}>Footer</footer>
    </div>
  )
}
