import React, { useEffect , setValue, setState, useState } from 'react'
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import Hero from '../components/Hero'
import Table from '../components/Table'
import Search from '../components/Search'
import { data } from "../components/megalo"


export default function Home() {

  const [query, setQuery] = useState('')
  const [mod, setMod] = useState([])
  
  const search = (data) => {
      return data.filter((jewel) => 
              jewel.name.toLowerCase().includes(query) || 
              jewel.description.toLowerCase().includes(query))
  }

  const addItem = (mod) => {
    setMod(prevMods => {
      return !prevMods.includes(mod) ? [...prevMods, mod] : [...prevMods]
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Megalomaniac Lurker</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
      <main className={styles.main}>
        <Search setQuery={setQuery} mods={mod} />
        <Table data={search(data)} addItem={addItem} />
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  )
}
